FROM node:lts-alpine as build-stage

RUN apk --no-cache add curl

RUN mkdir /app
WORKDIR /app

COPY package*.json ./
RUN npm i --legacy-peer-deps

COPY tsconfig.json tsconfig.json
COPY public public
COPY codegen.yml codegen.yml
COPY src src
COPY tailwind.config.js tailwind.config.js
COPY postcss.config.js postcss.config.js

ARG REACT_APP_GRAPHQL_API_URL
ENV REACT_APP_GRAPHQL_API_URL ${REACT_APP_GRAPHQL_API_URL}

RUN npm run build