query FetchMatchesFromAPI {
  fetchMatchesFromAPI {
    id
    stage
    group
    homeTeam {
      name
      crest
    }
    awayTeam {
      name
      crest
    }
    status
    utcDate
    score {
      winner
      duration
      fullTime {
        home
        away
      }
    }
  }
}