mutation updateAppStatus($data: UpdateAppStatusInput!) {
  updateAppSetting(data: $data) {
    id
    predictionsAreActivated
    predictionsRoundOf16Activated
    predictionsQuarterFinalsActivated
    predictionsSemiFinalsActivated
    predictionsFinalActivated
  }
}