mutation UpdatePrediction($updatePredictionId: Int!, $data: UpdatePredictionInput!) {
  updatePrediction(id: $updatePredictionId, data: $data) {
    id
    homeTeamScorePrediction
    awayTeamScorePrediction
  }
}