name: Compile and push client and server to production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push-server:
    uses: GrischK/Pronos-euro-des-potos/.github/workflows/build-server.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: grischk/pronos-des-potos_server

  build-and-push-client:
    uses: GrischK/Pronos-euro-des-potos/.github/workflows/build-client.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: grischk/pronos-des-potos_client